import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, Button, Badge } from '@/components/ui';
import { PageHeader } from '@/components/common';
const dashboardStats = [
    { label: 'Total Revenue', value: '$48,250', badge: '+12.5%', badgeVariant: 'success' },
    { label: 'Total Orders', value: '1,245', badge: '+8.3%', badgeVariant: 'info' },
    { label: 'Active Customers', value: '892', badge: '+15.2%', badgeVariant: 'primary' },
    { label: 'Net Profit', value: '$12,580', badge: '+10.1%', badgeVariant: 'secondary' },
];
export default function OwnerDashboard() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx(PageHeader, { title: "Owner Dashboard", description: "High-level overview of your business" }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4", children: dashboardStats.map((stat) => (_jsx(Card, { className: "overflow-hidden", children: _jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-[0.18em] text-neutral-500", children: stat.label }), _jsx("p", { className: "mt-4 text-3xl font-semibold text-neutral-900 dark:text-white", children: stat.value })] }), _jsx(Badge, { variant: stat.badgeVariant, size: "sm", children: stat.badge })] }) }, stat.label))) }), _jsxs("div", { className: "grid gap-6 xl:grid-cols-3", children: [_jsxs(Card, { className: "xl:col-span-2", children: [_jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: "Revenue Snapshot" }), _jsx("p", { className: "mt-1 text-sm text-neutral-500 dark:text-neutral-400", children: "Track weekly and monthly performance at a glance." })] }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(Button, { size: "sm", children: "Today" }), _jsx(Button, { variant: "outline", size: "sm", children: "This Month" }), _jsx(Button, { variant: "outline", size: "sm", children: "This Year" })] })] }), _jsx("div", { className: "mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4", children: [
                                    { label: 'Weekly Revenue', value: '$12,450' },
                                    { label: 'Monthly Revenue', value: '$48,250' },
                                    { label: 'Quarterly Revenue', value: '$142,800' },
                                    { label: 'Yearly Revenue', value: '$528,000' },
                                ].map((item) => (_jsxs("div", { className: "rounded-3xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-700 dark:bg-neutral-900", children: [_jsx("p", { className: "text-sm text-neutral-500", children: item.label }), _jsx("p", { className: "mt-3 text-xl font-semibold text-neutral-900 dark:text-white", children: item.value })] }, item.label))) })] }), _jsxs(Card, { children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: "Business Insights" }), _jsx("p", { className: "mt-1 text-sm text-neutral-500 dark:text-neutral-400", children: "Quick operational metrics for better decisions." })] }), _jsx(Badge, { variant: "info", size: "sm", children: "Stable" })] }), _jsx("div", { className: "mt-6 space-y-4", children: [
                                    { label: 'Profit Margin', value: '26.1%' },
                                    { label: 'Table Turnover', value: '3.8/day' },
                                    { label: 'Average Order Value', value: '$39.10' },
                                ].map((metric) => (_jsx("div", { className: "rounded-3xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-700 dark:bg-neutral-900", children: _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsx("p", { className: "text-sm text-neutral-500", children: metric.label }), _jsx("p", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: metric.value })] }) }, metric.label))) })] })] }), _jsx(Card, { children: _jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: "Owner Actions" }), _jsx("p", { className: "mt-1 text-sm text-neutral-500 dark:text-neutral-400", children: "Manage your business operations from a single view." })] }), _jsx("div", { className: "flex flex-wrap gap-3", children: ['Review Reports', 'Approve Budget', 'Publish Update', 'Invite Manager'].map((action) => (_jsx(Button, { variant: "outline", size: "sm", children: action }, action))) })] }) })] }));
}
