import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, Badge } from '@/components/ui';
import { PageHeader } from '@/components/common';
const revenueStreams = [
    { label: 'Dine-in Revenue', value: '$28,450', ratio: 59 },
    { label: 'Takeaway Revenue', value: '$12,800', ratio: 26.5 },
    { label: 'Delivery Revenue', value: '$7,000', ratio: 14.5 },
];
export default function Revenue() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx(PageHeader, { title: "Revenue", description: "Track revenue streams" }), _jsx("div", { className: "grid gap-4 md:grid-cols-2 xl:grid-cols-3", children: revenueStreams.map((item) => (_jsxs(Card, { className: "overflow-hidden", children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-[0.18em] text-neutral-500", children: item.label }), _jsx("p", { className: "mt-4 text-3xl font-semibold text-neutral-900 dark:text-white", children: item.value })] }), _jsxs(Badge, { variant: "success", size: "sm", children: [item.ratio, "%"] })] }), _jsx("div", { className: "mt-6 h-2 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800", children: _jsx("div", { className: "h-full rounded-full bg-primary-500", style: { width: `${item.ratio}%` } }) })] }, item.label))) }), _jsxs("div", { className: "grid gap-6 xl:grid-cols-3", children: [_jsxs(Card, { className: "xl:col-span-2", children: [_jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: "Monthly Revenue Breakdown" }), _jsx("p", { className: "mt-1 text-sm text-neutral-500 dark:text-neutral-400", children: "Compare revenue performance by month and channel." })] }), _jsx(Badge, { variant: "primary", size: "sm", children: "Full view" })] }), _jsx("div", { className: "mt-6 flex h-64 items-center justify-center rounded-3xl bg-neutral-50 text-sm text-neutral-400 dark:bg-neutral-900 dark:text-neutral-500", children: "Revenue chart placeholder" })] }), _jsxs(Card, { children: [_jsx("h2", { className: "text-lg font-semibold text-neutral-900 dark:text-white", children: "Revenue Highlights" }), _jsx("ul", { className: "mt-5 space-y-4", children: [
                                    { label: 'Best Month', value: 'December', valueDetail: '$65,400' },
                                    { label: 'Best Channel', value: 'Dine-in', valueDetail: '59%' },
                                    { label: 'Growth Rate', value: '12.5%', valueDetail: 'vs last year' },
                                ].map((item) => (_jsx("li", { className: "rounded-3xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-700 dark:bg-neutral-900", children: _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-neutral-500", children: item.label }), _jsx("p", { className: "mt-1 font-semibold text-neutral-900 dark:text-white", children: item.value })] }), _jsx("span", { className: "text-sm text-neutral-500", children: item.valueDetail })] }) }, item.label))) })] })] })] }));
}
