import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, Button, Input, Select } from '@/components/ui';
import { PageHeader } from '@/components/common';
export default function AdminSettings() {
    return (_jsxs("div", { children: [_jsx(PageHeader, { title: "Settings", description: "Manage restaurant settings" }), _jsxs("div", { className: "space-y-6 max-w-2xl", children: [_jsxs(Card, { children: [_jsx("h3", { className: "mb-4 font-semibold text-neutral-900 dark:text-white", children: "Restaurant Info" }), _jsxs("div", { className: "space-y-4", children: [_jsx(Input, { label: "Restaurant Name", defaultValue: "RestaurantOS" }), _jsx(Input, { label: "Email", type: "email", defaultValue: "contact@restaurantos.com" }), _jsx(Input, { label: "Phone", type: "tel", defaultValue: "+1-555-0000" }), _jsx(Input, { label: "Address", defaultValue: "123 Main Street, New York, NY 10001" })] })] }), _jsxs(Card, { children: [_jsx("h3", { className: "mb-4 font-semibold text-neutral-900 dark:text-white", children: "Business Hours" }), _jsx("div", { className: "space-y-4", children: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day) => (_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("span", { className: "w-24 text-sm font-medium text-neutral-700 dark:text-neutral-300", children: day }), _jsx(Select, { options: [
                                                { value: 'open', label: 'Open' },
                                                { value: 'closed', label: 'Closed' },
                                            ], defaultValue: "open" }), _jsx(Input, { type: "time", defaultValue: "09:00" }), _jsx("span", { className: "text-neutral-500", children: "to" }), _jsx(Input, { type: "time", defaultValue: "22:00" })] }, day))) })] }), _jsxs("div", { className: "flex justify-end gap-3", children: [_jsx(Button, { variant: "outline", children: "Reset" }), _jsx(Button, { children: "Save Settings" })] })] })] }));
}
